const mongoose = require('mongoose')
const UserScheme = require('./user')
const PostsCompanyScheme = require('./postsCompany')
// const portfolioSchema = require('./portfolio')
const companySchema = require('./company')
const ConnectionSchema = require('./connections')
const jobSchema = require('./jobs')
const PostsSchema = require('./posts')
const ConnectionsCompanySchema = require('./connectionCompany')

const User = mongoose.model('User', UserScheme)
// const Portfolio = mongoose.model('Portfolio', portfolioSchema)
const PostsCompany = mongoose.model('PostsCompany', PostsCompanyScheme)
const Company = mongoose.model('Company', companySchema)
const Connection = mongoose.model('Connection', ConnectionSchema)
const Job = mongoose.model('Job', jobSchema)
const Posts = mongoose.model('Posts', PostsSchema)
const ConnCompany = mongoose.model('ConnCompany', ConnectionsCompanySchema)

module.exports = { User, PostsCompany, Company, Connection, Job, Posts, ConnCompany }
